linters:
  enable-all: true
  disable:
    - goimports
    - deadcode
    - golint
    - varcheck
    - nosnakecase
    - ifshort
    - structcheck
    - scopelint
    - exhaustivestruct
    - maligned
    - interfacer
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - wastedassign
    - exhaustruct
    - gochecknoglobals
    - wsl
    - funlen
    - testpackage
    - gochecknoinits

linters-settings:
  gci:
    sections:
      - standard
      - blank
      - dot
      - default
      - prefix(github.com/mykysha/kubCalculator)

    skip-generated: true

    custom-order: true