# permissions for end users to edit calculators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: calculator-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubcalculator
    app.kubernetes.io/part-of: kubcalculator
    app.kubernetes.io/managed-by: kustomize
  name: calculator-editor-role
rules:
- apiGroups:
  - calc.example.com
  resources:
  - calculators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - calc.example.com
  resources:
  - calculators/status
  verbs:
  - get
